name: ci - lint - files - *.go, *.sum
on:
  push:
    branches: [main]
    paths: ["**/*.go", "go.sum", ".golangci.yml"]
  pull_request:
    branches: [main]
    paths: ["**/*.go", "go.sum", ".golangci.yml"]
jobs:
  lint-go:
    uses: natalie-o-perret/.github/.github/workflows/reusable-lint-files-go.yml@main
    with:
      go-version-file: go.mod
    secrets: inherit
