name: ci - lint - files - *.md, *.rst
on:
  push:
    branches: [main]
    paths: ["**/*.md", "**/*.rst", ".markdownlint.jsonc"]
  pull_request:
    branches: [main]
    paths: ["**/*.md", "**/*.rst", ".markdownlint.jsonc"]
jobs:
  markdown-lint:
    uses: natalie-o-perret/.github/.github/workflows/reusable-lint-files-md.yml@main
    secrets: inherit
