name: ci - lint - commits - conventional
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  conventional-commit:
    uses: natalie-o-perret/.github/.github/workflows/reusable-lint-commits-conventional.yml@main
    secrets: inherit
