name: ci - lint - files - *.json
on:
  push:
    branches: [main]
    paths: ["**/*.json", "**/*.jsonc"]
  pull_request:
    branches: [main]
    paths: ["**/*.json", "**/*.jsonc"]
jobs:
  json-lint:
    uses: natalie-o-perret/.github/.github/workflows/reusable-lint-files-json.yml@main
    secrets: inherit
