name: ci - lint - files - *.yml, *.yaml
on:
  push:
    branches: [main]
    paths: ["**/*.yml", "**/*.yaml", ".yamllint.yml"]
  pull_request:
    branches: [main]
    paths: ["**/*.yml", "**/*.yaml", ".yamllint.yml"]
jobs:
  yaml-lint:
    uses: natalie-o-perret/.github/.github/workflows/reusable-lint-files-yaml.yml@main
    secrets: inherit
